apiVersion: apps/v1
kind: Deployment
metadata:
  name: idefav-helloworld
  labels:
    app: idefav-helloworld
spec:
  replicas: 5
  selector:
    matchLabels:
      app: idefav-helloworld
  template:
    metadata:
      labels:
        app: idefav-helloworld
    spec:
      containers:
        - name: idefav-helloworld
          # mac m1 should choics image can support arm64,such as image e2eteam/echoserver:2.2-linux-arm64
          image: idefav/helloworld:build-ppl-with-buildpacks-run2.15-r-7nnfv
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: idefav-helloworld
  labels:
    app: idefav-helloworld
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: idefav-helloworld
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idefav-helloworld
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: idefav-helloworld.example.com
      http:
        paths:
          - backend:
              service:
                name: idefav-helloworld
                port:
                  number: 80
            path: /
            pathType: Prefix